/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boreykin.task1;

import java.util.Objects;

/**
 *
 * @author flyer
 */
public class Manager extends Employee
{
    private String department;
    
    public Manager(String firstName, String secondName, String lastName, String department) throws ForbiddenSymbols
    {
        super(firstName, secondName, lastName);
        this.department = department;
    }
    
    public Manager(String name, String department) throws WrongWordNumberInName, ForbiddenSymbols
    {
        super(name);
        this.department = department;
    }
    
    @Override
    public boolean equals(Object m)
    {
        return (m != null)
            && (m instanceof Manager)
            && (super.equals((Employee)m))
            && (((Manager)m).department.equals(this.department));
    }

    @Override
    public int hashCode() 
    {
        // Code of this method has been generated by IDE
        int hash = 5;
        hash = 41 * hash + Objects.hashCode(this.department);
        return hash;
    }
    
    public String getDepartment()
    {
        return this.department;
    }
    
    public void setDepartment(String department)
    {
        this.department = department;
    }
}
