/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boreykin.task1;

import java.util.Objects;

/**
 *
 * @author flyer
 */
public class Person 
{
    private static long personCount = 0;
    private static final String DEFAULT_FIRST_NAME = "DefaultFirstName";
    private static final String DEFAULT_LAST_NAME = "DefaultLastName";
    private static final int DEFAULT_BIRTH_YEAR = 0;
    private static final String DEFAULT_COUNTRY = "Nowhere";
    
    private String firstame;
    private String lastName;
    private int birthYear;
    private String country;
    
    public Person()
    {
        this(DEFAULT_FIRST_NAME,DEFAULT_LAST_NAME,DEFAULT_BIRTH_YEAR,DEFAULT_COUNTRY);
    }
    
    public Person(Person person)
    {
         this(person.firstame,person.lastName,person.birthYear,person.country);
    }
    
    public Person(String firstName, String lastName, int birthYear, String country)
    {
        personCount++;
        this.firstame = firstName;
        this.lastName = lastName;
        this.birthYear = birthYear;
        this.country = country;
    }
    
    @Override
    public int hashCode() 
    {
        // Generated by IDE
        int hash = 5;
        hash = 67 * hash + Objects.hashCode(this.firstame);
        hash = 67 * hash + Objects.hashCode(this.lastName);
        hash = 67 * hash + this.birthYear;
        hash = 67 * hash + Objects.hashCode(this.country);
        return hash;
    }

    @Override
    public boolean equals(Object obj) 
    {
        /*
         * To make the experiment with element search more "fair"
         * check for "obj" refers to "this" has not been added intentionally.
         */
        return (obj != null) 
            && (obj instanceof Person)
            && ((Person)obj).firstame.equals(this.firstame)
            && ((Person)obj).lastName.equals(this.lastName)
            && ((Person)obj).birthYear == this.birthYear
            && ((Person)obj).country.equals(this.country);
    }

   public static long getPersonCount() {
        return personCount;
    }

    public String getFirstame() {
        return firstame;
    }

    public void setFirstame(String firstame) {
        this.firstame = firstame;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public int getBirthYear() {
        return birthYear;
    }

    public void setBirthYear(int birthYear) {
        this.birthYear = birthYear;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }
}
